services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: https://api.intelinfo.me
        VITE_API_PORT: 8006
        NODE_ENV: production
        VITE_SOURCEMAP: false
    container_name: intelinfo-frontend
    ports:
      - "8004:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

