services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: intelinfo-frontend
    ports:
      - "80:80"
    environment:
      # If your frontend needs to call an existing backend, set it here.
      # Otherwise you can remove this line or set it at runtime:
      # VITE_BACKEND_URL=https://your-backend.example.com
      - VITE_BACKEND_URL=

